name: Go

on:
  pull_request:
    branches: [ "master" ] # master only accept PR, and every PR will be verify by this and branch protection rule

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.1

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if 1; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure -v
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
